# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97455733c81b354bc6925f1585f3c8995041cdb39d27f913b33b3dfb0dde50768d3b011c778b8f42890fda4395c1035c92577cfbe09585a1212ca7a4ea8df364

test:
  secret_key_base: 1e700d8edcc992bccea9a65ae4332187729c3b2a47585f055983078638131e57a07e092110aa1519b4250973339ad0f79d3bd056ea92c6a7645d5aed7495a1b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
